export type VisualType='primary_capture'|'physical_evidence'|'source_graphic'|'contextual_footage'|'generic_stock'|'end_card';
export interface QualityPolicies {primary_source_capture_min_ratio:number;source_backed_min_ratio:number;max_continuous_evidence_seconds:number;primary_capture_min_seconds:number;max_fullscreen_graphic_ratio:number;max_generic_stock_ratio:number;max_asset_reuse_count:number;max_motif_reuse_count:number;mobile_min_font_px:number;}
export interface Shot {id:string;section_id:string;start_frame:number;end_frame:number;visual_type:VisualType;asset:string;source_ids:string[];claim_ids:string[];source_backed:boolean;provenance_mode:'official_capture'|'physical_evidence'|'source_derived'|'licensed_footage'|'original';trim_in_seconds?:number;trim_out_seconds?:number;full_screen_graphic:boolean;motif:string;mobile_font_px?:number;transition:{type:'cut'|'crossfade'|'dip_to_black';duration_frames:number};music_cue?:string;narration_text:string;source_line?:string;}
export interface Section {id:string;title:string;start_frame:number;end_frame:number;}
export interface ProductionPlan {schema_version:1;project_id:string;title:string;fps:number;duration_frames:number;duration_seconds:number;proof:{minimum_seconds:number;boundary_frame:number;semantic_end:string;final_word:string};policies:QualityPolicies;sections:Section[];shots:Shot[];music_cues:Array<{id:string;asset:string;start_frame:number;end_frame:number;gain_db:number}>;}
export interface EditorialPause {after_word_index:number;after_source_second:number;duration_seconds:number;reason:string;}
export interface NarrationTimeline {schema_version:1;project_id:string;source_audio:string;source_audio_duration_seconds:number;editorial_pauses:EditorialPause[];output_duration_seconds:number;proof_semantic_end:string;proof_boundary_frame:number;final_word:string;timeline_sha256:string;}
export interface ProofApproval {schema_version:1;project_id:string;proof_prefix_sha256:string;narration_timeline_sha256:string;proof_run_id:string;render_source_commit:string;human_review_score:number;proof_boundary_frame:number;approved_at:string;}
export interface AuditResult {id:string;pass:boolean;applicable:boolean;measurements:Record<string,unknown>;thresholds:Record<string,unknown>;failures:string[];warnings:string[];}
